# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LqTWB2xwDu3ZhbdeLujgAYAeFxGKQ6k4
"""

import numpy as np
import pandas as pd


save_path = "/content/"

train_ = pd.read_pickle(save_path + "train_ood2.pkl")
valid_ = pd.read_pickle(save_path + "valid_ood2.pkl")
test_  = pd.read_pickle(save_path + "test_ood2.pkl")

data = pd.concat([train_, valid_, test_], axis=0)

print("Shapes:")
print("  train_:", train_.shape)
print("  valid_:", valid_.shape)
print("  test_ :", test_.shape)
print("  all   :", data.shape)

print("\nvalid_.head(2):")
print(valid_.head(2))
print("\ntest_.head(2):")
print(test_.head(2))


user_info = train_.groupby('uid').agg({'label': 'count'})
item_info = train_.groupby('iid').agg({'label': 'count'})

print("\nUser interaction stats (train_)")
print(user_info.describe())

print("\nItem interaction stats (train_)")
print(item_info.describe())

print("\n10% quantile for user counts:", user_info.quantile(0.1))
print("10% quantile for item counts:", item_info.quantile(0.1))

user_threshold = user_info['label'].quantile(0.2)
item_threshold = item_info['label'].quantile(0.2)

print("\nChosen user_threshold (20% quantile of counts):", user_threshold)
print("Chosen item_threshold (20% quantile of counts):", item_threshold)

warm_user_info = user_info[user_info['label'] > user_threshold]
warm_item_info = item_info[item_info['label'] > item_threshold]

warm_user = np.array(list(warm_user_info.index))
warm_item = np.array(list(warm_item_info.index))

print("\nNumber of users in train_:", user_info.shape[0])
print("Number of warm users    :", warm_user.shape[0])
print("Number of items in train_:", item_info.shape[0])
print("Number of warm items     :", warm_item.shape[0])

train_user = train_['uid'].unique()
train_item = train_['iid'].unique()

print("\ntrain_user shape:", train_user.shape)
print("train_item shape:", train_item.shape)


test_['warm'] = test_[['uid', 'iid']].apply(
    lambda x: (x.uid in warm_user) and (x.iid in warm_item),
    axis=1
).astype("int")

test_['cold'] = test_[['uid', 'iid']].apply(
    lambda x: (x.uid not in train_user) and (x.iid not in train_item),
    axis=1
).astype("int")


if 'not_cold' not in test_.columns:
    test_['not_cold'] = (1 - test_['cold']).astype("int")

print("\ntest_.head(5) after adding warm/cold:")
print(test_.head(5))

print("\nDistribution of warm / cold / not_cold in test_:")
print(test_[['warm', 'cold', 'not_cold']].describe())

out_path = save_path + "test_warm_cold_ood2.pkl"
test_.to_pickle(out_path)
print("\nSaved updated test_ with warm/cold to:", out_path)